collections:
  publications:
    output: false
  research-projects:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: research-projects
    values:
      is_research_project: true
